name: cescpro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: 4.7.3
  dio: 5.9.0
  pretty_dio_logger: 1.4.0
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  pull_to_refresh_flutter3: 2.0.2
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  event_bus: ^2.0.1
  logger: 2.6.1
  url_launcher: 6.3.2
  image_picker: 1.2.0
  path_provider: 2.1.5
  webview_flutter: 4.13.0
  keyboard_visibility_pro: 1.0.0
  app_settings: 6.1.1
  #电量
  #based_battery_indicator: ^1.0.3+1
  #cupertino_battery_indicator: ^1.2.1
  #realtime_battery_indicator: ^1.0.2
  #circular_menu: ^4.0.0
  #marquee: ^2.3.0
  marquee_widget: 1.2.0
  flutter_popup: 3.3.9
  flutter_datetime_picker_plus: 2.2.0
  intl: 0.20.2
  #时区
  timezone: ^0.10.1
  #图表
  fl_chart: 1.1.1
  #fl_chart_flutter:
  easy_date_timeline: 2.0.9
  calendar_date_picker2: 2.0.1
  easy_refresh: 3.4.0

  #国家数据
  country_state_city: 0.1.6
  #加载更多
  easy_load_more: 2.0.0
  collection: 1.19.1
  time_zone_plus: 0.0.4


  ####
  #custom_date_range_picker: ^1.2.0
  #calendar_date_picker2: 2.0.1
  #simple_month_year_picker: ^1.1.0
  #月选择
  #flutter_custom_month_picker: ^0.1.3


  #date_range_picker_flutter: ^1.0.2
  #custom_date_range_plus: ^0.0.3
#  mrx_charts: ^0.1.3
#  graphic: ^2.6.0
#  community_charts_flutter: ^1.0.4
#  material_charts: ^0.0.34
#  charts_painter: ^3.1.1
#  flutter_echarts: ^2.5.0
  #表格
  #flutter_expandable_table: ^2.1.0
  #日期表格calendar
#  table_calendar: ^3.2.0

  #选择日期
#  board_datetime_picker: ^2.8.2
#  cupertino_calendar_picker: ^2.2.6
#  flutter_popup: ^3.3.9
#  adoptive_calendar: ^0.2.0
  #横线的
#  flutter_datetime_picker_plus: ^2.2.0

  #漂亮的UI
  #syncfusion_flutter_datepicker: ^31.2.12
#  progressive_time_picker: ^1.0.3

  #flutter_echart: 2.0.0
  #extended_phone_number_input: ^1.0.2

  #图表-折线图
  #flutter_data_graph: ^0.0.9+1
  #fl_animated_linechart: ^1.2.0


  flutter_echart:
    path: plugins/flutter_echart-master
  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/img/
    - assets/gplot/
    - assets/json/


